name: Build Qt6 Application

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      QT_VERSION:      6.10.0
      BUILD_DIR:       D:\a\_temp\build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version:      ${{ env.QT_VERSION }}
          host:         windows
          target:       desktop
          arch:         win64_mingw
          use-official: true
          email:        ${{ secrets.QT_EMAIL }}
          pw:     ${{ secrets.QT_PW }}
          cache:        true

      - name: Create build directory
        run: |
          # On Windows PowerShell runner this will honor backslashes just fine.
          mkdir "${{ env.BUILD_DIR }}"

      - name: Build with qmake and make
        working-directory: ${{ env.BUILD_DIR }}
        run: |
          qmake6 "${{ github.workspace }}/Peggle_Roguelike.pro"
          mingw32-make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtAppBuild
          path: ${{ env.BUILD_DIR }}\release\PeggleRoguelike.exe
